### ISSUE TITLE
 TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by nickserv** [k23Burke/euro-rack#4]
## `npm start`
```
> euro-rack@1.0.0 start /Users/nick/Repos/euro-rack
> babel-node ./server/babel-start.js

url.js:102
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:102:11)
    at Object.urlParse [as parse] (url.js:96:5)
    at new Sequelize (/Users/nick/Repos/euro-rack/node_modules/sequelize/lib/sequelize.js:125:24)
    at Object.<anonymous> (/Users/nick/Repos/euro-rack/server/db/_db.js:4:12)
    at Module._compile (module.js:624:30)
    at loader (/Users/nick/Repos/euro-rack/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nick/Repos/euro-rack/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nick/Repos/euro-rack/server/db/index.js:1:1)
    at Module._compile (module.js:624:30)
    at loader (/Users/nick/Repos/euro-rack/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nick/Repos/euro-rack/node_modules/babel-register/lib/node.js:154:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! euro-rack@1.0.0 start: `babel-node ./server/babel-start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the euro-rack@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2017-10-12T04_12_40_205Z-debug.log
```

## `npms ls --depth 0`
```
euro-rack@1.0.0 /Users/nick/Repos/euro-rack
├── babel-cli@6.26.0
├── babel-core@6.26.0
├── babel-loader@6.4.1
├── babel-polyfill@6.26.0
├── babel-preset-es2015@6.24.1
├── babel-preset-react@6.24.1
├── body-parser@1.18.2
├── chai@3.5.0
├── chai-enzyme@0.6.1
├── chalk@1.1.3
├── cheerio@0.22.0
├── classnames@2.2.5
├── clean-webpack-plugin@0.1.17
├── cookie-parser@1.4.3
├── crypto@0.0.3
├── css-loader@0.26.4
├── dotenv@4.0.0
├── enzyme@2.9.1
├── express@4.16.2
├── fetch-polyfill@0.8.2
├── UNMET PEER DEPENDENCY file-loader@*
├── fs@0.0.1-security
├── immutable@3.8.2
├── jsdom@10.1.0
├── json-loader@0.5.7
├── jsonwebtoken@7.4.3
├── lodash@4.17.4
├── mocha@3.5.3
├── moment@2.19.1
├── node-sass@3.13.1
├── passport@0.3.2
├── pg@6.4.2
├── prop-types@15.6.0
├── react@15.6.2
├── react-addons-pure-render-mixin@15.6.2
├── react-addons-test-utils@15.6.2
├── react-dom@15.6.2
├── react-hot-loader@1.3.1
├── react-immutable-proptypes@2.1.0
├── react-redux@4.4.8
├── react-router@2.8.1
├── react-router-dom@4.2.2
├── react-router-scroll@0.3.3
├── redux@3.7.2
├── redux-api-middleware@1.0.3
├── redux-logger@2.10.2
├── sass-loader@3.2.3
├── sequelize@3.30.4
├── style-loader@0.13.2
├── tone@0.9.0
├── url-loader@0.5.9
├── uuid@3.1.0
├── webfontloader@1.6.28
├── webpack@1.15.0
├── webpack-dev-server@1.16.5
└── whatwg-fetch@0.11.1

npm ERR! peer dep missing: file-loader@*, required by url-loader@0.5.9
```

## Environment
- Node 8.6.0
- npm 5.5.1

**Comment by oftenfrequent** [comment]
Hey, I finally got around to updating the documentation and adding useful error logs. This commit 8790e209ac54cd5bc1ba7f0f4159098200d9fb71 should help you out getting a local version up and running
